# Generated by Django 5.2 on 2025-04-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_bookuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuser',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='otp',
        ),
    ]
