# Generated by Django 5.2 on 2025-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_remove_bookuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juice_type', models.CharField(choices=[('orange', 'Orange Juice'), ('apple', 'Apple Juice'), ('mango', 'Mango Juice')], max_length=50)),
                ('package_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
