# Generated by Django 5.2 on 2025-05-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
